# Generated by Django 2.2.24 on 2021-10-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Produto: ')),
                ('descricao_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição do Produto: ')),
                ('marca_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca do Produto: ')),
                ('custo_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custo do Produto: ')),
                ('preço_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preço do Produto: ')),
            ],
        ),
    ]
