# Generated by Django 2.2.24 on 2021-12-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaProdutos',
        ),
    ]
