# Generated by Django 2.2.24 on 2021-12-16 11:59

from django.db import migrations, models
import projeto.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_listaprodutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttConcluida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono_aparelho', models.CharField(blank=True, max_length=60, verbose_name='Dono do aparelho:')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo do aparelho:')),
                ('concerto', models.CharField(blank=True, max_length=600, verbose_name='Problema do aparelho:')),
                ('valor', models.CharField(blank=True, max_length=60, verbose_name='Valor do Concerto:')),
                ('data_da_manutencao', models.CharField(blank=True, max_length=60, verbose_name='Data entregue:')),
            ],
        ),
        migrations.CreateModel(
            name='AttPendete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(blank=True, max_length=60, verbose_name='Dono do aparelho:')),
                ('modelo_aparelho', models.CharField(blank=True, max_length=60, verbose_name='Modelo do aparelho:')),
                ('concerto_aparelho', models.CharField(blank=True, max_length=600, verbose_name='Problema do aparelho:')),
                ('valor_aparelho', models.CharField(blank=True, max_length=60, verbose_name='Valor do Concerto:')),
                ('data_entrega_aparelho', models.CharField(blank=True, max_length=60, verbose_name='Data para entregar:')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpagamento', models.CharField(blank=True, max_length=60, verbose_name='Metodo de Pagamento:')),
                ('descric', models.CharField(blank=True, max_length=60, verbose_name='Descrição:')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf_fiscal', models.CharField(blank=True, max_length=60, verbose_name='Codigo Fiscal')),
                ('valor_pago', models.CharField(blank=True, max_length=60, verbose_name='Valor Pago:')),
                ('data_venda', models.CharField(blank=True, max_length=60, verbose_name='Data da Venda:')),
                ('hora_venda', models.CharField(blank=True, max_length=60, verbose_name='Data da Venda:')),
                ('funcionario', models.CharField(blank=True, max_length=60, verbose_name='Funcionário:')),
                ('metodo_pago', models.CharField(max_length=100, null=True, verbose_name=projeto.core.models.MetodoPag)),
            ],
        ),
    ]
