# Generated by Django 2.2.24 on 2021-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211216_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='n_cliente',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nome do Cliente:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='nf_fiscal',
            field=models.CharField(blank=True, max_length=60, verbose_name='Codigo Fiscal:'),
        ),
    ]
