# Generated by Django 2.2.24 on 2022-01-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211217_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AguardandoRetirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cliente', models.CharField(max_length=60, verbose_name='Nome ')),
                ('m_aparelho', models.CharField(max_length=60, verbose_name='Modelo Do Aparelho ')),
                ('f_pagar_valor', models.CharField(blank=True, max_length=60, null=True, verbose_name='Valor a Pagar: ')),
                ('Falta_Pagar', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='core.Conclu_Serviço')),
            ],
        ),
    ]
