# Generated by Django 2.2.24 on 2022-02-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aguardandoretirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrada_saida_att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_ou_saida', models.CharField(blank=True, max_length=60, verbose_name='Compra ou Venda: ')),
                ('descric', models.CharField(blank=True, max_length=60, verbose_name='Descrição:')),
            ],
        ),
        migrations.CreateModel(
            name='mensal_diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensal_diario', models.CharField(blank=True, max_length=60, verbose_name='Diario ou Mensal: ')),
                ('descric', models.CharField(blank=True, max_length=60, verbose_name='Descrição:')),
            ],
        ),
        migrations.CreateModel(
            name='positivo_negativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiv_negativo', models.CharField(blank=True, max_length=60, verbose_name='Positivo ou Negativo: ')),
                ('descric', models.CharField(blank=True, max_length=60, verbose_name='Descrição:')),
            ],
        ),
        migrations.CreateModel(
            name='relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_r', models.CharField(blank=True, max_length=60, verbose_name='Valor: ')),
                ('motivo', models.CharField(blank=True, max_length=60, verbose_name='Produto: ')),
                ('data_r', models.CharField(blank=True, max_length=60, verbose_name='Data: ')),
                ('compra_ou_venda', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entrada_saida_att')),
            ],
        ),
        migrations.CreateModel(
            name='relatorio_mensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=60, verbose_name='Valor:')),
                ('mes_relatorio', models.CharField(blank=True, max_length=60, verbose_name='Mês do Relatório: ')),
                ('data_rm', models.CharField(blank=True, max_length=60, verbose_name='Mês do Relatório: ')),
                ('d_ou_m', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='core.mensal_diario')),
                ('p_ou_n', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='core.positivo_negativo')),
            ],
        ),
    ]
